* WEEK-01

** ODEVLER [/]

   - [ ] Aşağıdaki adreste yer alan "Veri Bilimi ve Yapay Zekaya Giriş" sınavı soruları çözülecek sınav sonuçları teams grubunda paylaşılacak.
         https://gelecegiyazanlar.turkcell.com.tr/konu/veri-bilimi-ve-yapay-zekaya-giris/egitim/101

   - [ ] Aşağıdaki adreste yer alan "Veri Okuryazarlığı" sınavı soruları çözülecek ve sınav sonuçları teams grubundan paylaşılacak:
         https://gelecegiyazanlar.turkcell.com.tr/konu/veri-okuryazarligi

   - [ ] TÜİK-OECD data yorumlama (isteğe bağlı)
         3 Avrupa ülkesini 3 metrik bazında değerlendirip 1 kısa paragraflık yorum yapma (% ler olursa havalı olur). 
         Yorum sonucunda ben gitseydim şu ülkeye giderdim diye belirteceğiz.

   - [ ] Konsoldan Python kodu çalıştırma 
         adım 1: hi.py isminde python dosyası oluştur 
         adım2: içine msj yaz 
         adım3: terminalden hi.py dizinine git 
         adım4: python hi.py kodunu çalıştır. 
         adım5: teams grubuna screen shot at. 

        not: 
          mac: ls ve cd komutları  windows: dir ve cd komutları  


    - [ ] Kullanıcıdan bilgi alma (input) ve çarpma fonksiyonunu konsol'dan yazdırmak (seçmeli)

    - [ ] Udemy'den veri yapıları bölümünde yer alan setler bölümü izlenecek.
